/* Hold the browser engine to the original scikit-survival pipeline.
 *
 *   node tests/verify.js
 *
 * Loads assets/engine.js — the exact file the page loads — plus
 * model/model.json, and replays every row of tests/reference_predictions.csv
 * (generated by tools/verify.py from the .joblib pipeline). Exits non-zero if
 * any linear predictor or survival probability drifts past the tolerance.
 *
 * Keep the CSV under version control: it lets anyone re-run this check without
 * the model object, the pinned Python environment, or any patient data.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const engine = require(path.join(ROOT, 'assets', 'engine.js'));
const model = JSON.parse(fs.readFileSync(path.join(ROOT, 'model', 'model.json'), 'utf8'));

const LP_TOLERANCE = 1e-9;
const SURVIVAL_TOLERANCE = 1e-9;

const csvPath = path.join(ROOT, 'tests', 'reference_predictions.csv');
if (!fs.existsSync(csvPath)) {
  console.error('Missing ' + path.relative(ROOT, csvPath) + '. Generate it with tools/verify.py.');
  process.exit(2);
}

const lines = fs.readFileSync(csvPath, 'utf8').trim().split('\n');
const header = lines[0].split(',');
const column = {};
header.forEach((name, i) => { column[name.trim()] = i; });

let worstLp = 0;
let worstSurvival = 0;
let failures = 0;
const horizons = [
  { days: 180, field: 's180' },
  { days: 360, field: 's360' },
  { days: 720, field: 's720' }
];

for (let row = 1; row < lines.length; row++) {
  const cells = lines[row].split(',');
  const values = ['albumin', 'platelet', 'afp', 'sodium', 'age']
    .map((name) => Number(cells[column[name]]));

  const lp = engine.score(model, values);
  const referenceLp = Number(cells[column.lp]);
  const lpDrift = Math.abs(lp - referenceLp);
  if (lpDrift > worstLp) worstLp = lpDrift;
  if (!(lpDrift <= LP_TOLERANCE)) {
    failures++;
    if (failures <= 5) {
      console.error(`row ${row}: linear predictor ${lp} vs ${referenceLp} (drift ${lpDrift.toExponential(3)})`);
    }
  }

  for (const h of horizons) {
    const s = engine.survival(model, h.days, lp);
    const referenceS = Number(cells[column[h.field]]);
    const drift = Math.abs(s - referenceS);
    if (drift > worstSurvival) worstSurvival = drift;
    if (!(drift <= SURVIVAL_TOLERANCE)) {
      failures++;
      if (failures <= 5) {
        console.error(`row ${row}: S(${h.days}) ${s} vs ${referenceS} (drift ${drift.toExponential(3)})`);
      }
    }
  }
}

const rows = lines.length - 1;
console.log(`3APNa engine check — ${rows} reference patients from ${model.source_model}`);
console.log(`  model version      ${model.version} (sha256 ${model.source_sha256.slice(0, 16)}…)`);
console.log(`  linear predictor   max |JS − Python| = ${worstLp.toExponential(3)}  (tolerance ${LP_TOLERANCE})`);
console.log(`  survival S(t)      max |JS − Python| = ${worstSurvival.toExponential(3)}  (tolerance ${SURVIVAL_TOLERANCE})`);

if (failures) {
  console.error(`\nFAILED — ${failures} comparison(s) outside tolerance.`);
  process.exit(1);
}

/* Structural invariant: with a single risk score and horizon-specific
   cut-offs, a patient's tier must never improve as the horizon lengthens.
   If it can, the cut-offs are inconsistent and the three cards would
   contradict each other. */
const order = { Low: 0, Intermediate: 1, High: 2 };
let monotoneFailures = 0;
for (let lp = -6; lp <= 6; lp += 0.001) {
  const tiers = model.horizons.map((h) => {
    const risk = 1 - engine.survival(model, h.days, lp);
    return order[engine.tier(model, risk, h.key)];
  });
  if (tiers[1] < tiers[0] || tiers[2] < tiers[1]) {
    if (monotoneFailures === 0) {
      console.error(`\nNon-monotone risk tiers at linear predictor ${lp.toFixed(3)}: ${tiers.join(' → ')}`);
    }
    monotoneFailures++;
  }
}
if (monotoneFailures) {
  console.error(`FAILED — risk tier can improve with a longer horizon (${monotoneFailures} points).`);
  process.exit(1);
}
console.log('  tier monotonicity  ok — tier never improves as the horizon lengthens');
console.log('\nPASSED');
